config/routes.rb
Haltertop::Application.routes.draw do
  match '/auth/facebook' => "sessions#redirect"

	resources :users
  resources :sessions,
    :only => [ :new, :create, :destroy ]

	# games paths, no one can edit or destroy a game
	resources :games, :except => [ :edit, :destroy ] do
		get 'move', :on => :member
    get 'pieces', :on => :member
	end

  root :to => "pages#home"

  match '/about'         => "pages#about"
  match '/contact'       => "pages#contact"

  match '/signin'        => "sessions#new"
  match '/signout'       => "sessions#destroy"
  match '/signup'        => "users#new"

	match '/play'					 => "games#create"
end

app/views/shared/_facebook_form.html.erb
<%= link_to facebook_url, :class => "facebook_link" do %>
<div class="facebook">
  <%= image_tag "f.png", :size => "40x40" %>
  <p>Login via Facebook</p>
</div>
<% end %>

app/views/shared/_full_user_form.html.erb
<%= form_for(@user) do |f| %>
  <p class="field">
    <%= f.text_field :name, :placeholder => "Name" %>
    <%= f.label :name %>
  </p>
  <p class="field">
    <%= f.text_field :email, :placeholder => "Email Address" %>
    <%= f.label :email %>
  </p>
  <p class="field">
    <%= f.password_field :password, :placeholder => "Password" %>
    <%= f.label :password %>
  </p>
  <p class="field">
    <%= f.password_field :password_confirmation, :placeholder => "Confirm Password" %>
    <%= f.label :password_confirmation %>
  </p>
  <p class="actions">
    <%= f.submit button_text, :class => "button orange" %>
  </p>
<% end %>

app/views/shared/_game_list.html.erb
<div class="game_list">
  <ul>
  <% games.each do |game| %>
    <%= render :partial => 'shared/versus', :locals => {:game => game } %>
  <% end %>
  </ul>
</div>

app/views/shared/_min_user_form.html.erb
<%= form_for(@user) do |f| %>
  <p class="field">
    <%= f.text_field :name, :placeholder => "Full Name" %>
  </p>
  <p class="field">
    <%= f.text_field :email, :placeholder => "Email" %>
  </p>
  <p class="field">
    <%= f.password_field :password, :placeholder => "Password" %>
  </p>
  <p class="field">
    <%= f.password_field :password_confirmation, :placeholder => "Confirm Password" %>
  </p>
  <p class="actions">
    <%= f.submit "Sign Up Now", :class => "button orange" %>
  </p>
<% end %>

app/views/shared/_quick_signup.html.erb
<%= render "shared/facebook_form" %>

<div style="height: 1px; background-color: black; text-align: center; margin-top: 15px; margin-bottom: 10px;">
  <span style="background-color: #f7f7f7; position: relative; top: -0.5em; padding: 0 3px 0;">
    OR
  </span>
</div>

<%= render "shared/min_user_form" %>

<p class="medium">Already have a password account?<br/><%= link_to "sign in here", signin_path %></p>

app/views/shared/_signin.html.erb
<%= form_for(:session, :url => sessions_path, :class => "signin") do |f| %>
  <div>
    <%= f.text_field :email, :size => '10', :placeholder => "Email Address" %>
    <%= f.password_field :password,  :size => '10', :placeholder => "Password" %>
    <%= f.submit "Sign in", :class => "button orange" %>
  </div>
<% end %>

app/views/shared/_user_bar.html.erb
<div class="userbar">
  <%= render :partial => 'users/user_box', :locals => { :user => @user } %>
  <p>Played: <%= pluralize(@user.games.count, "match") %></p>
  <p>Friends:</p>
  <ul class="friend_list">
  <% @friends.each do | f | %>
    <li><%= link_to f do %><%=  image_for f %><% end %></li>
  <% end %>
  </ul>
</div>

app/views/shared/_user_menu.html.erb
<!-- Menu shown to logged in users -->
<li><%= link_to "New Match", play_path, :class => "button orange medium" %></li>
<li><%= link_to "Current Matches", user_path(current_user), :class => "button gray medium" %></li>
<li><%= link_to "Settings", edit_user_path(current_user), :class => "button gray medium" %></li>
<li><%= link_to "Logout", signout_path, :class => "button gray medium" %></li>

app/views/shared/_versus.html.erb
<li class="versus round">
  <div class="left white_player">
    <%= (game.white.nil?) ? "Awaiting Player" : (current_user.id == game.white_id) ? "You" : game.white.name %>
    <%= image_for game.white %>
  </div>
  <div class="right black_player">
    <%= (game.black.nil?) ? "Awaiting Player" : (current_user.id == game.black_id) ? "You" : game.black.name %>
    <%= image_for game.black %>
  </div>
  <div class="center">
    <%= link_to game.get_button_text(current_user), game_path(game), :class => "button gray" %>
  </div>
</li>