config/routes.rb
Haltertop::Application.routes.draw do
  match '/auth/facebook' => "sessions#redirect"

	resources :users
  resources :sessions,
    :only => [ :new, :create, :destroy ]

	# games paths, no one can edit or destroy a game
	resources :games, :except => [ :edit, :destroy ] do
		get 'move', :on => :member
    get 'pieces', :on => :member
	end

  root :to => "pages#home"

  match '/about'         => "pages#about"
  match '/contact'       => "pages#contact"

  match '/signin'        => "sessions#new"
  match '/signout'       => "sessions#destroy"
  match '/signup'        => "users#new"

	match '/play'					 => "games#create"
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Blog", '#' %></li>
      <li><%= link_to "Twitter", "https://twitter.com/#!/Behindcurtain3" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <%= link_to image_tag("logo.png"), root_path, :class => "left" %>
    <nav>
      <ul>
    <% if signed_in? %>
        <%= render 'shared/user_menu' %>
    <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'haltertop.css' %>
  <%= javascript_include_tag "jquery-1.5.1.min.js" %>
  <%= javascript_include_tag 'rails' %>
  <%= include_gritter %>
</head>
<body>
<%= render 'layouts/header'  %>
<div class="container">
  <div class="content">
    <%= gflash %>
    <%= yield %>
  </div>
</div>
</body>
</html>